version: '3.5'

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER= ${DB_USER}
      - POSTGRES_PASSWORD= ${DB_PASSWORD}
      - POSTGRES_DB= ${DB_NAME}
    volumes:
      - ./db-data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  db_adminer:
    container_name: db_adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db


      